pipeline {
    agent { label 'ubuntu '}
    stages {
        stage('Prun Docker container') {
            steps {
                sh "docker system prune -a --volumes -f"
            }
        }

        stage('Run Docker Compose') {
            steps {
                sh "docker compose up -f test2/app/docker-compose.yaml -d --no-color --wait"
                sh "docker ps"
            }
        }

        stage('Run test') {
            steps {
                sh "curl http://localhost"
            }
        }
        
    }
       
}