pipeline {
    agent { label 'ubuntu' }
    
    environment {
        DOCKER_COMPOSE_PATH = 'test2/app'
    }

    stages {
        stage('Prune Docker container') {
            steps {
                script {
                    sh "docker system prune -a --volumes -f"
                }
            }
        }

        stage('Run Docker Compose') {
            steps {
                script {
                    dir(DOCKER_COMPOSE_PATH) {
                        sh 'docker compose up -d --no-color --wait'
                    }
                    sh 'docker ps'
                }
            }
        }

        stage('Run test') {
            steps {
                script {
                    def response = sh(script: 'curl -s -o /dev/null -w "%{http_code}" http://localhost', returnStdout: true).trim()
                    if (response != '200') {
                        error "Test failed with HTTP response code: ${response}"
                    } else {
                        echo "Test passed successfully! HTTP Response: ${response}"
                    }
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}
